In [2]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

* **5.1 Rerun the first cell in Section 5.1.2 to play against the MiniMax agent. Try your
best to win and see if the MiniMax agent can win the game.**

- A. cant defeat it

In [2]:
from utils.ttt_simple_env import ttt
from utils.ch05util import MiniMax_X, maximized_payoff 
import time

# Initiate the game environment
env=ttt()
state=env.reset()   
# Play a full game manually
while True:
    # Mesure how long it takes to come up with a move
    start=time.time()
    action = MiniMax_X(env)
    end=time.time()
    print(f"Player X has chosen action={action}") 
    print(f"It took the agent {end-start} seconds")     
    state, reward, done, info = env.step(action)
    print(f"Current state is \n{state.reshape(3,3)[::-1]}")
    if done:
        if reward==1:
            print("Player X has won!")  
        else:
            print("Game over, it's a tie!")
        break   
    action = input("Player O, what's your move?\n")
    print(f"Player O has chosen action={action}")    
    state, reward, done, info = env.step(int(action))
    print(f"Current state is \n{state.reshape(3,3)[::-1]}")
    if done:
        print("Player O has won!") 
        break

Player X has chosen action=7
It took the agent 16.141022205352783 seconds
Current state is 
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Player O has chosen action=5
Current state is 
[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0  0]]
Player X has chosen action=9
It took the agent 0.32250356674194336 seconds
Current state is 
[[ 1  0  1]
 [ 0 -1  0]
 [ 0  0  0]]
Player O has chosen action=8
Current state is 
[[ 1 -1  1]
 [ 0 -1  0]
 [ 0  0  0]]
Player X has chosen action=2
It took the agent 0.012089729309082031 seconds
Current state is 
[[ 1 -1  1]
 [ 0 -1  0]
 [ 0  1  0]]
Player O has chosen action=3
Current state is 
[[ 1 -1  1]
 [ 0 -1  0]
 [ 0  1 -1]]
Player X has chosen action=1
It took the agent 0.0007777214050292969 seconds
Current state is 
[[ 1 -1  1]
 [ 0 -1  0]
 [ 1  1 -1]]
Player O has chosen action=4
Current state is 
[[ 1 -1  1]
 [-1 -1  0]
 [ 1  1 -1]]
Player X has chosen action=6
It took the agent 0.00014543533325195312 seconds
Current state is 
[[ 1 -1  1]
 [-1 -1  1]
 [ 1  1 -1]]
Game over, it's a 

* **5.2 Define a function MiniMax_XO() so that it applies to both Player X and Player
O. Your goal is to replace MiniMax_X() and MiniMax_O() with one single
function MiniMax_XO().**


In [6]:
from copy import deepcopy
from utils.ttt_simple_env import ttt
from utils.ch05util import maximized_payoff 
from random import choice
import time

def MiniMax_XO(env):
    wins=[]
    ties=[]
    losses=[]  
    # iterate through all possible next moves
    for m in env.validinputs:
        # make a hypothetical move and see what happens
        env_copy=deepcopy(env)
        state,reward,done,info=env_copy.step(m) 
        # If player X wins right away with move m, take it.
        if env_copy.turn=="X":
            if done and reward==1:
                return m
        elif env_copy.turn=="O":
            if done and reward==-1:
                return m
        # See what's the best response from the opponent
        opponent_payoff=maximized_payoff(env_copy,reward,done)  
        # Opponent's payoff is the opposite of your payoff
        my_payoff=-opponent_payoff 
        if my_payoff==1:
            wins.append(m)
        elif my_payoff==0:
            ties.append(m)
        else:
            losses.append(m)
    # pick winning moves if there is any        
    if len(wins)>0:
        return choice(wins)
    # otherwise pick tying moves
    elif len(ties)>0:
        return choice(ties)
    return env.sample()

# Initiate the game environment
env=ttt()
state=env.reset()   
# Play a full game manually
while True:
    # Mesure how long it takes to come up with a move
    start=time.time()
    action = MiniMax_XO(env)
    end=time.time()
    print(f"Player X has chosen action={action}") 
    print(f"It took the agent {end-start} seconds")     
    state, reward, done, info = env.step(action)
    print(f"Current state is \n{state.reshape(3,3)[::-1]}")
    if done:
        if reward==1:
            print("Player X has won!")  
        else:
            print("Game over, it's a tie!")
        break   
    # action = input("Player O, what's your move?\n")
    action = MiniMax_XO(env)
    print(f"Player O has chosen action={action}")    
    state, reward, done, info = env.step(int(action))
    print(f"Current state is \n{state.reshape(3,3)[::-1]}")
    if done:
        print("Player O has won!") 
        break

Player X has chosen action=1
It took the agent 16.61863088607788 seconds
Current state is 
[[0 0 0]
 [0 0 0]
 [1 0 0]]
Player O has chosen action=5
Current state is 
[[ 0  0  0]
 [ 0 -1  0]
 [ 1  0  0]]
Player X has chosen action=2
It took the agent 0.21727609634399414 seconds
Current state is 
[[ 0  0  0]
 [ 0 -1  0]
 [ 1  1  0]]
Player O has chosen action=3
Current state is 
[[ 0  0  0]
 [ 0 -1  0]
 [ 1  1 -1]]
Player X has chosen action=7
It took the agent 0.005934238433837891 seconds
Current state is 
[[ 1  0  0]
 [ 0 -1  0]
 [ 1  1 -1]]
Player O has chosen action=4
Current state is 
[[ 1  0  0]
 [-1 -1  0]
 [ 1  1 -1]]
Player X has chosen action=6
It took the agent 0.0004260540008544922 seconds
Current state is 
[[ 1  0  0]
 [-1 -1  1]
 [ 1  1 -1]]
Player O has chosen action=8
Current state is 
[[ 1 -1  0]
 [-1 -1  1]
 [ 1  1 -1]]
Player X has chosen action=9
It took the agent 4.0531158447265625e-05 seconds
Current state is 
[[ 1 -1  1]
 [-1 -1  1]
 [ 1  1 -1]]
Game over, it's a t

* **5.3 Rerun the first cell in Section 5.3.1 to play against the MiniMax agent in Con-
nect Four. Try your best to win and see what happens.**

In [12]:
from utils.conn_simple_env import conn
from utils.ch05util import MiniMax_depth
# Initiate the game environment
env=conn()
state=env.reset()   
# Play a full game manually
while True:
    # Mesure how long it takes to come up with a move
    start=time.time()
    action=MiniMax_depth(env,depth=3)
    end=time.time()
    print(f"The red player has chosen action={action}") 
    print(f"It took the agent {end-start} seconds")     
    state, reward, done, info = env.step(action)
    print(f"the current state is \n{state.T[::-1]}")
    if done:
        if reward==1:
            print(f"The red player has won!")  
        else:
            print("Game over, it's a tie!")
        break   
    action=input("Player yellow, what's your move?\n")
    print(f"Player yellow has chosen action={action}")    
    state, reward, done, info = env.step(int(action))
    print(f"the current state is \n{state.T[::-1]}")
    if done:
        if reward==-1:
            print(f"The yellow player has won!")  
        else:
            print("Game over, it's a tie!")
        break                   

The red player has chosen action=1
It took the agent 0.12539267539978027 seconds
the current state is 
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
Player yellow has chosen action=2
the current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 1 -1  0  0  0  0  0]]
The red player has chosen action=4
It took the agent 0.11878633499145508 seconds
the current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 1 -1  0  1  0  0  0]]
Player yellow has chosen action=2
the current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0]
 [ 1 -1  0  1  0  0  0]]
The red player has chosen action=7
It took the agent 0.12213253974914551 seconds
the current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0 