In [2]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

In [2]:
!uv pip install tensorflow

Using Python 3.12.10 environment at: /home/anon-labs/Documents/projects/AlphaGoSimplified/.venv
Audited 1 package in 3ms


In [2]:
import tensorflow as tf
model=tf.keras.models.load_model('/home/anon-labs/projects/AlphaGoSimplified/files/value_conn.h5')

2025-10-07 23:14:47.801341: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-07 23:14:47.841042: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-07 23:14:48.853342: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
/home/anon-labs/Documents/projects/AlphaGoSimplified/.venv/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

* **8.1 Modify the first two cells in Section 8.2 so that the MCTS agent uses the
strategy defined in the function mcts() instead of the naive strategy. See how
many times the MCTS agent has won and lost.**

In [5]:
from utils.coin_env import coin_game
from utils.ch08util import naive_mcts

results=[]
for i in range(100):
    env=coin_game()
    state=env.reset() 
    if i%2==0:
        action=env.sample()
        state, reward, done, info=env.step(action)
    while True:
        action=naive_mcts(env,num_rollouts=1000)  
        state, reward, done, info=env.step(action)
        if done:
            # result is 1 if the MCTS agent wins
            results.append(1) 
            break  
        action=env.sample()   
        state, reward, done, info=env.step(action)
        if done:
            # result is -1 if the MCTS agent loses
            results.append(-1) 
            break              

In [6]:
# count how many times the MCTS agent won
wins=results.count(1)
print(f"the MCTS agent has won {wins} games")
# count how many times the MCTS agent lost
losses=results.count(-1)
print(f"the MCTS agent has lost {losses} games")         

the MCTS agent has won 95 games
the MCTS agent has lost 5 games


In [11]:
from utils.coin_env import coin_game
from utils.ch08util import naive_mcts, mcts

results=[]
for i in range(100):
    env=coin_game()
    state=env.reset() 
    if i%2==0:
        action=env.sample()
        state, reward, done, info=env.step(action)
    while True:
        action=naive_mcts(env,num_rollouts=1000)  
        state, reward, done, info=env.step(action)
        if done:
            # result is 1 if the MCTS agent wins
            results.append(1) 
            break  
        action=env.sample()   
        state, reward, done, info=env.step(action)
        if done:
            # result is -1 if the MCTS agent loses
            results.append(-1) 
            break              

In [12]:
# count how many times the MCTS agent won
wins=results.count(1)
print(f"the MCTS agent has won {wins} games")
# count how many times the MCTS agent lost
losses=results.count(-1)
print(f"the MCTS agent has lost {losses} games")         

the MCTS agent has won 95 games
the MCTS agent has lost 5 games


* **8.2 Modify the first code cell in Section 8.4.1 so that the MCTS agent uses 20000
rollouts when making moves. Try your best to win the game yourself and see if
the MCTS agent can win the game.**

- cant be defeated

In [14]:
from utils.ttt_simple_env import ttt
from utils.ch08util import mcts

env=ttt()
state=env.reset() 
while True:
    action=mcts(env,num_rollouts=20000)
    print(f"Player {env.turn} has chosen {action}")    
    state, reward, done, info = env.step(action)
    print(f"Current state is \n{state.reshape(3,3)[::-1]}")
    if done:
        if reward==1:
            print(f"Player {env.turn} has won!") 
        else:
            print("Game over, it's a tie!")    
        break  
    action=int(input("What's your move?"))
    print(f"Player {env.turn} has chosen {action}")    
    state, reward, done, info = env.step(action)
    print(f"Current state is \n{state.reshape(3,3)[::-1]}")
    if done:
        print(f"Player {env.turn} has won!")  
        break

Player X has chosen 5
Current state is 
[[0 0 0]
 [0 1 0]
 [0 0 0]]
Player O has chosen 1
Current state is 
[[ 0  0  0]
 [ 0  1  0]
 [-1  0  0]]
Player X has chosen 2
Current state is 
[[ 0  0  0]
 [ 0  1  0]
 [-1  1  0]]
Player O has chosen 8
Current state is 
[[ 0 -1  0]
 [ 0  1  0]
 [-1  1  0]]
Player X has chosen 7
Current state is 
[[ 1 -1  0]
 [ 0  1  0]
 [-1  1  0]]
Player O has chosen 3
Current state is 
[[ 1 -1  0]
 [ 0  1  0]
 [-1  1 -1]]
Player X has chosen 4
Current state is 
[[ 1 -1  0]
 [ 1  1  0]
 [-1  1 -1]]
Player O has chosen 6
Current state is 
[[ 1 -1  0]
 [ 1  1 -1]
 [-1  1 -1]]
Player X has chosen 9
Current state is 
[[ 1 -1  1]
 [ 1  1 -1]
 [-1  1 -1]]
Game over, it's a tie!


* **8.3 Modify the first two code cells in Section 8.4.2 so that the MCTS agent uses
20000 rollouts when making moves. See how many games the MCTS agent has
won and lost.**

In [15]:
import random

results=[]
for i in range(100):
    state=env.reset() 
    if i%2==0:
        action=env.sample()
        state, reward, done, info=env.step(action)
    while True:
        action=mcts(env,num_rollouts=20000)  
        state, reward, done, info=env.step(action)
        if done:
            # result is 1 if the MCTS agent wins
            if reward!=0:
                results.append(1) 
            else:
                results.append(0)    
            break  
        action=env.sample()   
        state, reward, done, info=env.step(action)
        if done:
            # result is -1 if the random-move agent wins
            if reward!=0:
                results.append(-1) 
            else:
                results.append(0)    
            break  

In [16]:
# count how many times the MCTS agent won
wins=results.count(1)
print(f"the MCTS agent has won {wins} games")
# count how many times the MCTS agent lost
losses=results.count(-1)
print(f"the MCTS agent has lost {losses} games")  
# count how many tie games
losses=results.count(0)
print(f"the game is tied {losses} times") 

the MCTS agent has won 90 games
the MCTS agent has lost 6 games
the game is tied 4 times


* **8.4 Modify the first code cell in Section 8.5.1 so that the MCTS agent uses 10000
rollouts when making moves. Try your best to win the game yourself and see if
the MCTS agent can win the game.**

In [17]:
from utils.conn_simple_env import conn

# Initiate the game environment
env=conn()
state=env.reset() 
while True:
    action=mcts(env,num_rollouts=1000)
    print(f"Player {env.turn} has chosen {action}")    
    state, reward, done, info=env.step(action)
    print(f"Current state is \n{state.T[::-1]}")
    if done:
        print("Player red has won!") 
        break
    action=int(input("What's your move?"))
    print(f"Player {env.turn} has chosen {action}")    
    state, reward, done, info=env.step(action)
    print(f"Current state is \n{state.T[::-1]}")
    if done:
        if reward!=0:
            print("Player yellow has won!") 
        else:
            print("Game over, it's a tie!")    
        break  

Player red has chosen 4
Current state is 
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]]
Player yellow has chosen 1
Current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [-1  0  0  1  0  0  0]]
Player red has chosen 5
Current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [-1  0  0  1  1  0  0]]
Player yellow has chosen 2
Current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [-1 -1  0  1  1  0  0]]
Player red has chosen 6
Current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [-1 -1  0  1  1  1  0]]
Player yellow has chosen 2
Current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0 

* **8.5 Modify the two code cells in Section 8.5.2 so that the MCTS agent uses 10000
rollouts when making moves. See how many games the MCTS agent has won
and lost in Connect Four.**

In [18]:
# MCTS vs Random agent
results=[]
for i in range(100):
    state=env.reset() 
    if i%2==0:
        action=env.sample()
        state, reward, done, info=env.step(action)
    while True:
        action=mcts(env,num_rollouts=10_000)  
        state, reward, done, info=env.step(action)
        if done:
            # result is 1 if the MCTS agent wins
            results.append(abs(reward)) 
            break  
        action=env.sample()  
        state, reward, done, info=env.step(action)
        if done:
            # result is -1 if the MCTS agent loses
            results.append(-abs(reward)) 
            break  

In [19]:
# count how many times the MCTS agent won
wins=results.count(1)
print(f"the MCTS agent has won {wins} games")
# count how many times the MCTS agent lost
losses=results.count(-1)
print(f"the MCTS agent has lost {losses} games")  
# count how many tie games
losses=results.count(0)
print(f"the game is tied {losses} times") 

the MCTS agent has won 100 games
the MCTS agent has lost 0 games
the game is tied 0 times
