In [2]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

* **6.1 Rerun the first cell in Section 6.2.3 and enter moves with your keyboard to play
against the MiniMax agent with alpha-beta pruning. Try your best to win and
see if you can beat the agent. See how long it takes for the agent to come up
with a move on your computer.**

In [4]:
from utils.ch06util import MiniMax_ab
from utils.ttt_simple_env import ttt
import time

# Initiate the game environment
env=ttt()
state=env.reset()   
# Play a full game manually
while True:
    # Mesure how long it takes to come up with a move
    start=time.time()
    action=MiniMax_ab(env)
    end=time.time()
    print(f"Player X has chosen action={action}") 
    print(f"It took the agent {end-start} seconds")     
    state, reward, done, info = env.step(action)
    print(f"Current state is \n{state.reshape(3,3)[::-1]}")
    if done:
        if reward==1:
            print(f"Player X has won!")  
        else:
            print("Game over, it's a tie!")
        break   
    action = input("Player O, what's your move?\n")
    print(f"Player O has chosen action={action}")    
    state, reward, done, info = env.step(int(action))
    print(f"Current state is \n{state.reshape(3,3)[::-1]}")
    if done:
        print(f"Player O has won!") 
        break

Player X has chosen action=2
It took the agent 1.0153164863586426 seconds
Current state is 
[[0 0 0]
 [0 0 0]
 [0 1 0]]
Player O has chosen action=5
Current state is 
[[ 0  0  0]
 [ 0 -1  0]
 [ 0  1  0]]
Player X has chosen action=4
It took the agent 0.07293581962585449 seconds
Current state is 
[[ 0  0  0]
 [ 1 -1  0]
 [ 0  1  0]]
Player O has chosen action=6
Current state is 
[[ 0  0  0]
 [ 1 -1 -1]
 [ 0  1  0]]
Player X has chosen action=1
It took the agent 0.006705284118652344 seconds
Current state is 
[[ 0  0  0]
 [ 1 -1 -1]
 [ 1  1  0]]
Player O has chosen action=3
Current state is 
[[ 0  0  0]
 [ 1 -1 -1]
 [ 1  1 -1]]
Player X has chosen action=7
It took the agent 0.00024437904357910156 seconds
Current state is 
[[ 1  0  0]
 [ 1 -1 -1]
 [ 1  1 -1]]
Player X has won!


* **6.2 Rerun the two code cells in Section 6.3 to see the game outcomes when the MiniMax agent with alpha-beta pruning plays against the MiniMax agent without
alpha-beta pruning in Tic Tac Toe.**

In [ ]:
from utils.ch05util import MiniMax_X,MiniMax_O
from utils.ch02util import one_ttt_game 

results=[]
for i in range(10):
    # MiniMax with pruning moves first if i is an even number
    if i%2==0:
        result=one_ttt_game(MiniMax_ab,MiniMax_O)
        # record game outcome
        results.append(result)
    # MiniMax with pruning moves second if i is an odd number
    else:
        result=one_ttt_game(MiniMax_X,MiniMax_ab)
        # record negative game outcome
        results.append(-result)

In [5]:
# count how many times MiniMax with alpha-beta pruning won
wins=results.count(1)
print(f"MiniMax with alpha-beta pruning won {wins} games")
# count how many times MiniMax with alpha-beta pruning lost
losses=results.count(-1)
print(f"MiniMax with alpha-beta pruning lost {losses} games")
# count tie games
ties=results.count(0)
print(f"the game was tied {ties} times")          

MiniMax with alpha-beta pruning won 0 games
MiniMax with alpha-beta pruning lost 0 games
the game was tied 10 times


* **6.3 Rerun the first cell in Section 6.4.2 to play against the MiniMax agent with
alpha-beta pruning in Connect Four. See how long it takes for the agent to
come up with a move on your computer.**

In [10]:
from utils.ch06util import MiniMax_conn
from utils.conn_env import conn
import time

# Initiate the game environment
env=conn()
state=env.reset()   
# Play a full game manually
while True:
    # Mesure how long it takes to come up with a move
    start=time.time()
    action=MiniMax_conn(env,depth=3)
    end=time.time()
    print(f"The red player has chosen action={action}") 
    print(f"It took the agent {end-start} seconds")     
    state, reward, done, info = env.step(action)
    print(f"Current state is \n{state.T[::-1]}")
    if done:
        if reward==1:
            print(f"The red player has won!")  
        else:
            print("Game over, it's a tie!")
        break   
    action=input("Player yellow, what's your move?\n")
    print(f"Player yellow has chosen action={action}")    
    state, reward, done, info = env.step(int(action))
    print(f"Current state is \n{state.T[::-1]}")
    if done:
        if reward==-1:
            print(f"The yellow player has won!")  
        else:
            print("Game over, it's a tie!")
        break                   

The red player has chosen action=4
It took the agent 0.01790618896484375 seconds
Current state is 
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]]
Player yellow has chosen action=1
Current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [-1  0  0  1  0  0  0]]
The red player has chosen action=1
It took the agent 0.017311573028564453 seconds
Current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0]
 [-1  0  0  1  0  0  0]]
Player yellow has chosen action=2
Current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0]
 [-1 -1  0  1  0  0  0]]
The red player has chosen action=7
It took the agent 0.021595001220703125 seconds
Current state is 
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0 

* **6.4 Rerun the two code cells in Section 6.4.3 to see the game outcomes when the
MiniMax agent with alpha-beta pruning plays against the MiniMax agent without
alpha-beta pruning in Connect Four.**

In [11]:
from utils.ch05util import MiniMax_depth
from utils.ch03util import one_conn_game 

results=[]
for i in range(100):
    # MiniMax with pruning moves first if i is even 
    if i%2==0:
        result=one_conn_game(MiniMax_conn,MiniMax_depth)
        # record game outcome
        results.append(result)
    # MiniMax with pruning moves second if i is odd 
    else:
        result=one_conn_game(MiniMax_depth,MiniMax_conn)
        # record negative game outcome
        results.append(-result)

In [12]:
# count how many times MiniMax with alpha-beta pruning won
wins=results.count(1)
print(f"MiniMax with alpha-beta pruning won {wins} games")
# count how many times MiniMax with pruning lost
losses=results.count(-1)
print(f"MiniMax with alpha-beta pruning lost {losses} games")
# count tie games
ties=results.count(0)
print(f"the game was tied {ties} times")               

MiniMax with alpha-beta pruning won 43 games
MiniMax with alpha-beta pruning lost 45 games
the game was tied 12 times
