3.2.1 From Python lists to PyTorch tensors

* see list indexing in action

In [9]:
# modified. to access data
!git clone https://github.com/deep-learning-with-pytorch/dlwpt-code.git

%cd dlwpt-code/p1ch2

Cloning into 'dlwpt-code'...
remote: Enumerating objects: 706, done.
remote: Counting objects: 100% (152/152), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 706 (delta 107), reused 89 (delta 87), pack-reused 554 (from 1)
Receiving objects: 100% (706/706), 175.17 MiB | 27.03 MiB/s, done.
Resolving deltas: 100% (319/319), done.
Updating files: 100% (228/228), done.
/content/dlwpt-code/p1ch2


In [10]:
a = [1.0, 2.0, 1.0]

In [11]:
a[0]

1.0

In [12]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

3.2.2 Constructing our first tensors

In [13]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [14]:
a[1]

tensor(1.)

In [15]:
float(a[1])

1.0

In [16]:
a[2] = 2.0
a

tensor([1., 1., 2.])

**3.2.3 Essence of tensors:**

 PyTorch tensors or NumPy
arrays, on the other hand, are views over (typically) contiguous memory blocks containing unboxed C numeric types rather than Python objects.

In [17]:
points = torch.zeros(6) # <1> Using .zeros is just a way to get an appropriately sized array.
points[0] = 4.0 # <2> We overwrite those zeros with the values we actually want.
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [18]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [19]:
# To get the coordinates of the first point
float(points[0]), float(points[1])

(4.0, 1.0)

In [20]:
# using 2D tensor for point representation
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points.shape

torch.Size([3, 2])

In [22]:
# we could also use zeros or ones to initialize the tensor, providing the size as a tuple:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [23]:
# Now we can access an individual element in the tensor using two indices
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [24]:
points[0, 1]

tensor(1.)

In [25]:
points[0]

tensor([4., 1.])

In [26]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

<ipython-input-26-8575ff47c9e0>:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [27]:
points_storage = points.storage()
points_storage[0]

4.0

In [28]:
points.storage()[1]

1.0

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [31]:
second_point.size()

torch.Size([2])

In [32]:
second_point.shape

torch.Size([2])

In [33]:
points.stride()

(2, 1)

In [34]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [35]:
second_point.storage_offset()

2

In [36]:
second_point.stride()

(1,)

In [37]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [39]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [40]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [41]:
id(points.storage()) == id(points_t.storage())

False

In [42]:
points.stride()

(2, 1)

In [43]:
points_t.stride()

(1, 2)

In [44]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [45]:
transpose_t.shape

torch.Size([5, 4, 3])

In [46]:
some_t.stride()

(20, 5, 1)

In [47]:
transpose_t.stride()

(1, 5, 20)

In [48]:
points.is_contiguous()

True

In [49]:
points_t.is_contiguous()

False

In [50]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [51]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [52]:
points_t.stride()

(1, 2)

In [53]:
# make it contiguous
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [54]:
points_t_cont.stride()

(3, 1)

In [55]:
points_t_cont.storage() # storage has been re-stored

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [56]:
# change the data type
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [57]:
short_points.dtype

torch.int16

In [58]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [59]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [60]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [61]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [62]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [63]:
points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>Adds a dimension of size 1, just like unsqueeze

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

* To and from numpy
* shares same underlying cache with numpy so it is fast

In [64]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [65]:
points = torch.from_numpy(points_np)

In [66]:
torch.save(points, '../data/p1ch3/ourpoints.t')

* save and load tensor from file

In [67]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [68]:
points = torch.load('../data/p1ch3/ourpoints.t')

<ipython-input-68-9163bc48809f>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  points = torch.load('../data/p1ch3/ourpoints.t')


In [69]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

<ipython-input-69-491a49d59d1c>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  points = torch.load(f)


# 2.1 Serializing to HDF5 with h5py

In [70]:
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [71]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [72]:
last_points = torch.from_numpy(dset[-2:])
f.close()

* cpu / gpu

In [73]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [74]:
points_gpu = points.to(device='cuda')

In [75]:
points_gpu = points.to(device='cuda:0') # 0 (default) is index of gpu for multi-gpu pc

In [76]:
points = 2 * points  # <1> Multiplication performed on the CPU
points_gpu = 2 * points.to(device='cuda')  # <2> Multiplication performed on the GPU

In [77]:
points_gpu = points_gpu + 4

In [78]:
points_cpu = points_gpu.to(device='cpu')

In [79]:
# Shorthand method for cuda and cpu
points_gpu = points.cuda()  # <1> Defaults to GPU index 0
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [80]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [81]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [82]:
a = torch.ones(3, 2)

In [83]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])